#!/bin/sh
#
#  File: lint.sh - run clang-tidy over the project sources
#
#  Copyright (C) 2026 Sinan Islekdemir <sinan@islekdemir.com>
#
#  Requires build/compile_commands.json (generated by cmake, see AGENTS.md).
#
#  Usage:
#    scripts/lint.sh                 # lint everything (except src/vendor)
#    scripts/lint.sh src/core/foo.c  # lint specific file(s)
#
set -eu

cd "$(dirname "$0")/.."

if [ ! -f build/compile_commands.json ]; then
  echo "error: build/compile_commands.json not found." >&2
  echo "Run: cmake -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON" >&2
  exit 1
fi

if [ "$#" -gt 0 ]; then
  run-clang-tidy -quiet -p build "$@"
else
  run-clang-tidy -quiet -p build 'src/(?!vendor).*\.(c|cpp)$'
fi
